language: cpp
sudo: required
dist: xenial
compiler:
- g++
os:
- linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55
        packages:
            - gcc-5
            - g++-5
            - cmake
            - cmake-data


branches:
  only:
  - master

install:
    # Checking versions
    - g++ --version

script: ./run_build.sh

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}

notifications:
  email:
    - malcolm.watt@mail.mcgill.ca

env:
  global:
  - LANG="en_US.UTF-8"